version: '2'
services:
    openstackclient:
        build: ./openstackclient
        image: openstack/openstackclient
    identity:
        build: ./keystone
        image: openstack/keystone
        ports:
            - "35357:35357"
            - "5000:5000"
        volumes:
            - ./etc/identity/keystone:/etc/keystone
            - ./log/identity/keystone:/var/log/apache2
        restart: always
        depends_on:
            - identity_db
        links:
            - identity_db
    identity_db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: keystone
            MYSQL_USER: keystone
            MYSQL_PASSWORD: password
    image:
        build: ./glance
        image: openstack/glance
        ports:
            - "9292:9292"
        volumes:
            - ./etc/image/glance:/etc/glance
            - ./log/image/glance:/var/log/glance
        restart: always
        depends_on:
            - image_db
        links:
            - image_db
    image_db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: glance
            MYSQL_USER: glance
            MYSQL_PASSWORD: password
    nova:
        build: ./nova
        image: openstack/nova
        privileged: true
        ports:
            - "8774:8774"
        volumes:
            - ./etc/controller/nova:/etc/nova
            - ./log/controller/nova:/var/log/nova
        networks:
            default:
                ipv4_address: 172.18.0.100
        restart: always
        depends_on:
            - nova_db
            - nova_api_db
            - nova_rabbitmq
        links:
            - nova_db
            - nova_api_db
            - nova_rabbitmq
    nova_db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: nova
            MYSQL_USER: nova
            MYSQL_PASSWORD: password
    nova_api_db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: nova_api
            MYSQL_USER: nova_api
            MYSQL_PASSWORD: password
    nova_rabbitmq:
        image: rabbitmq
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: nova
            RABBITMQ_DEFAULT_PASS: password
    neutron:
        build: ./neutron
        image: openstack/neutron
        privileged: true
        ports:
            - "9696:9696"
        volumes:
            - ./etc/network/neutron:/etc/neutron
            - ./log/network/neutron:/var/log/neutron
        networks:
            default:
                ipv4_address: 172.18.0.20
        restart: always
        depends_on:
            - neutron_db
            - neutron_rabbitmq
        links:
            - neutron_db
            - neutron_rabbitmq
    neutron_db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: neutron
            MYSQL_USER: neutron
            MYSQL_PASSWORD: password
    neutron_rabbitmq:
        image: rabbitmq
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: neutron
            RABBITMQ_DEFAULT_PASS: password
