version: '2'
services:
    keystone:
        image: openstack/keystone
        ports:
            - "35357:35357"
            - "5000:5000"
        volumes:
            - etc/keystone:/etc/keystone
        depends_on:
            - keystone_db
        links:
            - keystone_db
        restart: always
        environment:
            MYSQL_DATABASE: keystone
            MYSQL_USER: keystone
            MYSQL_PASSWORD: password
    keystone_db:
        image: mysql
        volumes:
            - "./.data/keystone_db:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: keystone
            MYSQL_USER: keystone
            MYSQL_PASSWORD: password
