version: '2'
services:
    openstackclient:
        build: ./openstackclient
        image: openstack/openstackclient
    keystone:
        build: ./keystone
        image: openstack/keystone
        ports:
            - "35357:35357"
            - "5000:5000"
        volumes:
            - ./etc/keystone:/etc/keystone
            - ./log/keystone:/var/log/apache2
        restart: always
        depends_on:
            - keystone_db
        links:
            - keystone_db
    keystone_db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: keystone
            MYSQL_USER: keystone
            MYSQL_PASSWORD: password
    glance:
        build: ./glance
        image: openstack/glance
        ports:
            - "9292:9292"
        volumes:
            - ./etc/glance:/etc/glance
            - ./log/glance:/var/log/glance
        restart: always
        depends_on:
            - glance_db
        links:
            - glance_db
    glance_db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: glance
            MYSQL_USER: glance
            MYSQL_PASSWORD: password
    nova:
        build: ./nova
        image: openstack/nova
        ports:
            - "8774:8774"
        volumes:
            - ./etc/nova:/etc/nova
            - ./log/nova:/var/log/nova
        restart: always
        depends_on:
            - nova_db
            - nova_api_db
        links:
            - nova_db
            - nova_api_db
    nova_db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: nova
            MYSQL_USER: nova
            MYSQL_PASSWORD: password
    nova_api_db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: nova_api
            MYSQL_USER: nova_api
            MYSQL_PASSWORD: password
